### ISSUE TITLE
API create/update response does not include changes applied by Laravel Eloquent events

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#243]
Note: Testing with v1.0.0-beta.2 to put off migration work however as far as I am aware this issue is not changed on subsequent releases up to beta.5 per the release notes.

In my case, I have Eloquent saving / creating / updating events which are performing a correctness check in a case with a somewhat complex parent/child hierarchy which is tracked with a "parent_id" ID number attribute on the models. The events are performing a consistency check, and rather than throwing a bunch of errors for no reason and to allow a hierarchy change with only one API event, I am checking and making a bunch of changes to multiple models to resolve what would otherwise be a hierarchy conflict. Sometimes this involves editing the model which itself is updated via the API call before saving.

When this occurs (server-side automatic edits to models which are both the subject of the API call as well as some related models via the Eloquent saving / updating / creating events), and the response is commanded to include some related models for example, the server-side changes which are applied to the root model are not reflected in the response however the changes made to all other models are reflected in the "include" response. I can confirm that Laravel itself is applying the changes and committing them to the database but the API response does not reflect that. It's as though the API has buffered the Eloquent object before the saving/updating/creating event and does not reflect changes, however it probably is newly querying for "include" resources and so those changes are reflected.

I get that directly editing attributes on the saving/updating/creating method parameters is not exactly kosher but it works and Laravel accepts it so I figure so should the API response for consistency reasons.

Environment:
- PHP 7.1
- Laravel 5.5
- laravel-json-api v1.0.0-beta.2

**Comment by SirLamer** [comment]
Here is a code sample, this is currently quite difficult to follow but for now, here ya go.

Important things to understand:
- "deviceGroup" has many "devices", every "device" has one "deviceGroup"
- "device" may have one "parent" which itself is a "device" 
- If "parent_id" is null then that Device is expected to be the top of the hierarchy for the given "deviceGroup"
- In my application a "device" may easily be changed to be a member of a different "deviceGroup" or a device's "parent" may easily be changed, or both at once. A logical conflict (such as if a device's parent stays a member of the old deviceGroup) is meant to be quietly resolved automatically.

So the symptom to note is that at the end of the "updating" event, the model has been revised to feature the correct and expected "parent_id" however the JSON API response will not reflect this.

```php
    /**
     * @param Device $model
     */
    public function updating($model)
    {
        $old = $model->getOriginal();
        \Log::debug('Device updating', ['model' => $model, 'old' => $old]);

        // Clean-up actions when Device is assigned a new Device Group
        if ($model->device_group_id !== $old['device_group_id'] && $model->parent_id !== null) {
            \Log::debug('DeviceGroup changed with non-null parent ID', ['parent_id' => $model->parent_id]);
            /** @var DeviceGroup $deviceGroup */
            $deviceGroup = $model->deviceGroup;
            $parent = $model->parent;

            // If parent Device is not a member of the new Device Group, abandon it
            if ($parent && !$deviceGroup->devices->contains($parent)) {
                $model->parent_id = $deviceGroup->topDevice->id ?? null;
                \Log::debug('100 parent_id assign', ['id' => $model->id, 'parent_id' => $model->parent_id]);
            }
        }

        // If parent field is null, take that to mean this Device is the new top parent for the Device Group
        if ($model->parent_id === null
            && ($old['parent_id'] !== null || $model->device_group_id !== $old['device_group_id'])
        ) {
            \Log::debug('Parent is null');
            $deviceGroup = $model->deviceGroup;
            $parent = $deviceGroup->topDevice;

            if ($parent) {
                \Log::debug('Group has parent', ['parent' => $parent]);
                $parent->children->where('id', '!=', $model->id)->each(function ($device) use ($model) {
                    $device->parent_id = $model->id;
                    \Log::debug('Child parent assign', ['id' => $device->id, 'parent_id' => $device->parent_id]);
                    $device->save();
                });

                $parent->parent_id = $model->id;
                \Log::debug('Parent reassignment', ['id' => $parent->id, 'parent_id' => $parent->parent_id]);
                $parent->save();
            }
        }

        if ($model->device_group_id !== $old['device_group_id']) {
            \Log::debug('DeviceGroup changed', ['new' => $model->device_group_id, 'old' => $old['device_group_id']]);
            $children = $model->children;

            if ($children->count() !== 0) {
                if ($old['parent_id'] === null) {
                    $top = $children->sortBy('designation')->first();
                    \Log::debug('Replacing parent on children', ['ids' => $children->pluck('id')->toArray(), 'parent' => $top->id]);
                    $children->each(function ($device) use ($top) {
                        $device->parent_id = $device->id === $top->id ? null : $top->id;
                        $device->save();
                    });
                } else {
                    \Log::debug('Replacing DeviceGroup on children', ['ids' => $children->pluck('id')->toArray(), 'deviceGroup' => $model->device_group_id]);
                    $children->each(function ($device) use ($model) {
                        $device->device_group_id = $model->device_group_id;
                        $device->save();
                    });
                }
            } else {
                \Log::debug('No children');
            }
        }

        \Log::debug('Model state before save', ['device' => $model]);
    }
```

And the very verbose log output:
```txt
[2018-10-15 17:53:49] local.DEBUG: DeviceGroup changed with non-null parent ID {"parent_id":180} 
[2018-10-15 17:53:49] local.DEBUG: 100 parent_id assign {"id":195,"parent_id":192} 
[2018-10-15 17:53:49] local.DEBUG: DeviceGroup changed {"new":48,"old":47} 
[2018-10-15 17:53:49] local.DEBUG: No children  
[2018-10-15 17:53:49] local.DEBUG: Model state before save {"device":"[object] (App\\Models\\Building\\Device: {\"id\":195,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":1,\"designation\":\"14\",\"slug\":\"14\",\"licence\":null,\"created_at\":\"2018-06-04 15:57:59\",\"updated_at\":\"2018-10-15 15:34:19\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\",\"devices\":[{\"id\":192,\"building_id\":49,\"device_group_id\":48,\"parent_id\":null,\"device_type_id\":2,\"designation\":\"11\",\"slug\":\"11\",\"licence\":null,\"created_at\":\"2018-06-04 15:39:37\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":193,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":2,\"designation\":\"12\",\"slug\":\"12\",\"licence\":null,\"created_at\":\"2018-06-04 15:51:47\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":196,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":2,\"designation\":\"15\",\"slug\":\"15\",\"licence\":null,\"created_at\":\"2018-06-04 16:03:11\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":197,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":2,\"designation\":\"16\",\"slug\":\"16\",\"licence\":null,\"created_at\":\"2018-06-04 16:13:36\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":198,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":2,\"designation\":\"17\",\"slug\":\"17\",\"licence\":null,\"created_at\":\"2018-06-04 16:18:10\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":229,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":1,\"designation\":\"13\",\"slug\":\"13\",\"licence\":\"E123456\",\"created_at\":\"2018-09-29 05:16:39\",\"updated_at\":\"2018-10-03 03:02:56\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":230,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":2,\"designation\":\"18\",\"slug\":\"18\",\"licence\":null,\"created_at\":\"2018-10-01 05:01:52\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}},{\"id\":232,\"building_id\":49,\"device_group_id\":48,\"parent_id\":192,\"device_type_id\":1,\"designation\":\"19\",\"slug\":\"19\",\"licence\":\"E001234\",\"created_at\":\"2018-10-01 05:03:45\",\"updated_at\":\"2018-10-03 00:08:24\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}}],\"top_device\":{\"id\":192,\"building_id\":49,\"device_group_id\":48,\"parent_id\":null,\"device_type_id\":2,\"designation\":\"11\",\"slug\":\"11\",\"licence\":null,\"created_at\":\"2018-06-04 15:39:37\",\"updated_at\":\"2018-10-01 14:32:09\",\"device_group\":{\"id\":48,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"test\",\"slug\":\"test\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-01 14:32:09\"}}},\"parent\":{\"id\":180,\"building_id\":49,\"device_group_id\":47,\"parent_id\":null,\"device_type_id\":1,\"designation\":\"01\",\"slug\":\"01\",\"licence\":null,\"created_at\":\"2018-04-17 16:40:50\",\"updated_at\":\"2018-10-15 04:36:33\",\"device_group\":{\"id\":47,\"building_id\":49,\"device_type_id\":1,\"parent_id\":null,\"name\":\"Main\",\"slug\":\"main\",\"created_at\":\"2018-09-23 03:10:15\",\"updated_at\":\"2018-10-03 23:21:43\"}},\"children\":[]})"} 
```

API response (with a very verbose collection of included resources for validation purposes)
```json
{"data":{"type":"devices","id":"195","attributes":{"designation":"14","licence":null,"slug":"14"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},"included":[{"type":"devices","id":"178","attributes":{"designation":"03","licence":null,"slug":"03"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},{"type":"devices","id":"179","attributes":{"designation":"02","licence":null,"slug":"02"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},{"type":"devices","id":"180","attributes":{"designation":"01","licence":null,"slug":"01"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[{"type":"devices","id":"178"},{"type":"devices","id":"179"},{"type":"devices","id":"181"},{"type":"devices","id":"182"},{"type":"devices","id":"186"}]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":null},"projects":[]}},{"type":"devices","id":"181","attributes":{"designation":"04","licence":null,"slug":"04"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},{"type":"devices","id":"182","attributes":{"designation":"05","licence":null,"slug":"05"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},{"type":"devices","id":"183","attributes":{"designation":"07","licence":null,"slug":"07"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"186"}},"projects":[]}},{"type":"devices","id":"184","attributes":{"designation":"08","licence":null,"slug":"08"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"186"}},"projects":[]}},{"type":"devices","id":"185","attributes":{"designation":"09","licence":null,"slug":"09"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"186"}},"projects":[]}},{"type":"devices","id":"186","attributes":{"designation":"06","licence":null,"slug":"06"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[{"type":"devices","id":"183"},{"type":"devices","id":"184"},{"type":"devices","id":"185"},{"type":"devices","id":"187"}]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"180"}},"projects":[]}},{"type":"devices","id":"187","attributes":{"designation":"10","licence":null,"slug":"10"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"47"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"186"}},"projects":[]}},{"type":"devices","id":"192","attributes":{"designation":"11","licence":null,"slug":"11"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[{"type":"devices","id":"193"},{"type":"devices","id":"195"},{"type":"devices","id":"196"},{"type":"devices","id":"197"},{"type":"devices","id":"198"},{"type":"devices","id":"229"},{"type":"devices","id":"230"},{"type":"devices","id":"232"}]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":null},"projects":[]}},{"type":"devices","id":"193","attributes":{"designation":"12","licence":null,"slug":"12"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"196","attributes":{"designation":"15","licence":null,"slug":"15"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"197","attributes":{"designation":"16","licence":null,"slug":"16"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"198","attributes":{"designation":"17","licence":null,"slug":"17"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"229","attributes":{"designation":"13","licence":"E123456","slug":"13"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"230","attributes":{"designation":"18","licence":null,"slug":"18"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"devices","id":"232","attributes":{"designation":"19","licence":"E001234","slug":"19"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"children":{"data":[]},"device-group":{"data":{"type":"device-groups","id":"48"}},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":{"type":"devices","id":"192"}},"projects":[]}},{"type":"device-groups","id":"47","attributes":{"name":"Main","slug":"main"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"devices":{"data":[{"type":"devices","id":"178"},{"type":"devices","id":"179"},{"type":"devices","id":"180"},{"type":"devices","id":"181"},{"type":"devices","id":"182"},{"type":"devices","id":"183"},{"type":"devices","id":"184"},{"type":"devices","id":"185"},{"type":"devices","id":"186"},{"type":"devices","id":"187"}]},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":null},"projects":[]}},{"type":"device-groups","id":"48","attributes":{"name":"test","slug":"test"},"relationships":{"building":{"data":{"type":"buildings","id":"49"}},"devices":{"data":[{"type":"devices","id":"192"},{"type":"devices","id":"193"},{"type":"devices","id":"195"},{"type":"devices","id":"196"},{"type":"devices","id":"197"},{"type":"devices","id":"198"},{"type":"devices","id":"229"},{"type":"devices","id":"230"},{"type":"devices","id":"232"}]},"device-type":{"data":{"type":"device-types","id":"1"}},"inspections":[],"parent":{"data":null},"projects":[]}},{"type":"buildings","id":"49","attributes":{"name":"Address Test","slug":"address-test"},"relationships":{"address":{"data":{"type":"addresses","id":"56"}},"devices":{"data":[{"type":"devices","id":"178"},{"type":"devices","id":"179"},{"type":"devices","id":"180"},{"type":"devices","id":"181"},{"type":"devices","id":"182"},{"type":"devices","id":"183"},{"type":"devices","id":"184"},{"type":"devices","id":"185"},{"type":"devices","id":"186"},{"type":"devices","id":"187"},{"type":"devices","id":"192"},{"type":"devices","id":"193"},{"type":"devices","id":"195"},{"type":"devices","id":"196"},{"type":"devices","id":"197"},{"type":"devices","id":"198"},{"type":"devices","id":"229"},{"type":"devices","id":"230"},{"type":"devices","id":"232"}]},"device-groups":{"data":[{"type":"device-groups","id":"47"},{"type":"device-groups","id":"48"}]},"projects":[]}}]}
```

On "model state before save", the "parent_id" of "192" is expected and correct but the API response still shows the original "180" which is a logical conflict.

**Comment by lindyhopchris** [comment]
There's a lot to process here, so this is my guess as to what's going on... this is to do with Eloquent relation caching, not JSON API caching...

If the related parent has already been accessed on the model, then it will be cached in the model. Changing the `parent_id` will not cause the cached related parent to change - this is how Eloquent works.

So to change a relationship you'd be better using the Eloquent relation `associate/dissociate` methods. E.g. this line:

```php
$device->parent_id = $device->id === $top->id ? null : $top->id;
```

Should be:

```php
$top ? $device->parent()->associate($top) : $device->parent()->dissociate();
```

If you want to stick with changing the ids, then you need to call `refresh` on the models that are altered.

**Comment by lindyhopchris** [comment]
> It's as though the API has buffered the Eloquent object before the saving/updating/creating event and does not reflect changes

The same instance of the model is used throughout the API, so if relations aren't updated and the internal Eloquent cache keeps the previous relations, then the changes won't appear in the encoded response.

This line:

`$parent = $model->parent;`

In the clean up action causes the related parent (with ID 180) to be cached internally within `$model`

**Comment by lindyhopchris** [comment]
@SirLamer did you get this one solved?

**Comment by SirLamer** [comment]
I tried using "attached" and "detached" but I don't think this changed outcomes since Laravel is just editing the ID number field when you use these methods anyway.

I agree that this has to do with how Laravel caches things. Up to you if you want to account for this.

For my case I ran in to asynchronous race condition issues and others things external to the API itself so for now I am taking a different approach (client has to command all of the model changes, server validates).

**Comment by lindyhopchris** [comment]
So we do account for it when we're updating relationships by doing this:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/AbstractAdapter.php#L386-L389

So maybe in this case just adding a `$model->refresh()` to the end of your `updating` method would solve the problem?

Anyway, as you've found a different approach I'll close the issue. Race conditions are always a problem if you are updating multiple different resources from a single resource - it's definitely best to avoid this is possible. The JSON API spec is probably going to add something to deal with multiple updates in a single request, though this is multiple updates from the client's perspective, rather than the server's:
https://github.com/json-api/json-api/pull/1254
